### ISSUE TITLE
Not compatible with your version of node/npm

### ISSUE THREAD

**Issue by leolionart** [madchicken/homebridge-prometheus-exporter#4]
Unsupported engine for find-my-way@7.7.0: wanted: {"node":">=14"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: find-my-way@7.7.0
npm WARN notsup Unsupported engine for toad-cache@3.3.0: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: toad-cache@3.3.0
npm WARN notsup Unsupported engine for real-require@0.2.0: wanted: {"node":">= 12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: real-require@0.2.0
npm WARN notsup Unsupported engine for on-exit-leak-free@2.1.2: wanted: {"node":">=14.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: on-exit-leak-free@2.1.2
npm WARN notsup Unsupported engine for readable-stream@4.4.2: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: readable-stream@4.4.2

**Comment by madchicken** [comment]
Sorry, I don't know what are you talking about: this project does not use npm or node at all. It's a binary compiled from Rust code.
